Templated adding traders to trader manager
northwesternfintech/NUTC pull request #123
Opened 2024-03-27 02:09 UTC by stevenewald

2024-03-27 02:10 UTC, stevenewald commented
Also added names to remote trader

2024-03-27 04:04 UTC, egelja requested changes

2024-03-27 04:04 UTC, egelja commented on exchange/src/exchange/algos/normal_mode/normal_mode.cpp
> +                                + user["lastName"].get<std::string>();
use `fmt` not str concatenation its more readable

2024-04-06 01:43 UTC, glasss13 approved these changes

2024-04-07 02:42 UTC, merged