limit order
northwesternfintech/NUTC pull request #188
Opened 2024-05-21 07:10 UTC by efang05

renamed market order to limit order then added actual market orders

2024-05-22 04:17 UTC, stevenewald requested changes
Can we add some tests as well?

2024-05-28 21:53 UTC, glasss13 commented on linter/src/pywrapper/runtime.hpp
> +        publish_limit_order
To keep the code consistnent, we should probably make this function take in both `publish_limit_order` and `publish_market_order` like how it is in `exchange`

2024-05-28 22:33 UTC, glasss13 commented on exchange/test/test_algos/confirm_market_order.py
> +    """Place a market order - DO NOT MODIFY"""
We should probably add this to the actual template as well.

2024-05-29 17:48 UTC, stevenewald commented
Also pls merge with main @efang05

2024-06-19 18:07 UTC, stevenewald commented on exchange/test/src/integration/basic.cpp
> +    cycle.wait_for_order({buy, "APPL", 1, 1000});
Shouldn't we be waiting for the market order? Why does buy_market_order place a limit order?

2024-06-22 17:11 UTC, glasss13 commented
I think you accidentally included RSI bot into this PR

2024-06-26 18:46 UTC, stevenewald commented
I'm gonna wrap this up because I made some changes that broke it, good work @efang05

2024-06-30 19:36 UTC, merged