Fix overlapping port number and update timeout
northwesternfintech/NUTC pull request #53
Opened 2023-11-20 22:01 UTC by glasss13

Port 8080 is already in use by the linter.

2023-11-20 22:21 UTC, egelja requested changes

2023-11-20 22:21 UTC, egelja commented on sandbox-server/main.go
> +const port = "8000"
```suggestion
const port = "8081"
```

2023-11-21 14:37 UTC, egelja approved these changes
lgtm

also good job keeping a nice commit history

2023-11-21 15:03 UTC, stevenewald commented
Is this for local development? If not, it's unnecessary as they aren't running on the same machine

2023-11-21 17:00 UTC, glasss13 commented
> Is this for local development? If not, it's unnecessary, as they aren't running on the same machine.

Oh, I wasn't familiar with how it would end up being run. I'll revert that, then. Still worth updating the sandbox timeout regardless I think since we forgot to change that from the testing value.

2023-11-21 18:43 UTC, egelja commented
I’d say it’s fine. We can just remap in docker if needed. 

Just merge

2023-11-22 18:02 UTC, merged